# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33e3052e30fe9b70fa197e49fd149cc5c43ba2bb90c02e0d5137bab1a2ad4f2d0389d3a8b3c66358b4025f69e606b9ada2aab79744327d484c7407f60a43f05

test:
  secret_key_base: 97e6629dfdd57ad9f462c76fafa43a687dbfb6a08e6ab0304caa33dadcb03c2171096a8723c50b1c07d1337ce01059df53591436389e70f3f71cc6e3b19401b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
